version: '2'

#networks:
#  default:
#    external:
#      name: ci

services:
  consul:
    image: gliderlabs/consul-server:latest
    hostname: consul
    ports:
      - 8300:8300
      - 8400:8400
      - 8500:8500
      - 8600:53/udp
    command: -data-dir /tmp/consul -bootstrap -client 0.0.0.0
    environment:
      - SERVICE_8300_NAME=consul-rpc-server
      - SERVICE_8300_TAGS=consul,rpc,server
      - SERVICE_8400_NAME=consul-rpc-client
      - SERVICE_8400_TAGS=consul,rpc,client
      - SERVICE_8500_NAME=consul-http-api
      - SERVICE_8500_TAGS=consul,http,api
      - SERVICE_53_NAME=consul-dns
      - SERVICE_8500_TAGS=consul,dns
      - SERVICE_TAGS=service-discovery

  registrator:
    image: gliderlabs/registrator:latest
    hostname: registrator
    links:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: consul://consul:8500

  git:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: git
    ports:
      - 80:80
    volumes:
      - /srv/gitlab/config:/etc/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/data:/var/opt/gitlab
    environment:
      - SERVICE_80_NAME=git
      - SERVICE_TAGS=scm

#  gitrunner:
#    image: gitlab/gitlab-runner:ubuntu-v1.5.3
#    restart: always
#    links:
#     - git
#    hostname: gitrunner
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - /tmp/gitlab-runner/config:/etc/gitlab-runner

  nexus:
    image: sonatype/nexus3
    hostname: nexus
    ports:
      - 8081:8081
      - 8443:8443
    environment:
      - SERVICE_8081_NAME=nexus
      - SERVICE_8443_NAME=nexus-https
      - SERVICE_TAGS=repository,binary

  jenkins:
    hostname: jenkins
    image: jenkinsci/jenkins
#    volumes:
#      - /srv/jenkins_home:/opt/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
    links:
      - consul
      - registrator
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - SERVICE_8080_NAME=jenkins
      - SERVICE_50000_NAME=jenkinscli
      - SERVICE_TAGS=ci,build,master
      - SERVICE_8080_CHECK_HTTP=/
      - SERVICE_8080_CHECK_INTERVAL=5s
